#!/bin/sh

echo "------ HOOK START - BUILD -------"
#printenv
#set -x

BUILD_ARGS=
[ "$DOCKER_TAG" = "latest" ] || BUILD_ARGS='--build-arg BRANCH=master'

docker build $BUILD_ARGS -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
